import {
  AppstoreOutlined,
  BarChartOutlined,
  CalculatorOutlined,
  DashboardOutlined,
  DollarCircleOutlined,
  ExperimentOutlined,
  InboxOutlined,
  SettingOutlined,
  ShopOutlined,
  ShoppingCartOutlined,
  TeamOutlined,
  ToolOutlined,
  TruckOutlined,
} from "@ant-design/icons";

import type { AdminModuleNavigation } from "@/types/navigation";

export const adminModules: AdminModuleNavigation[] = [
  {
    key: "hoje",
    label: "Hoje",
    path: "/admin/hoje",
    icon: <DashboardOutlined />,
    description: "Visao diaria com leitura segura do legado e indicadores principais.",
    section: "principal",
    topbarItems: [
      { key: "resumo", label: "Resumo", path: "/admin/hoje", accent: "primary" },
      { key: "agenda", label: "Agenda", path: "/admin/hoje/agenda" },
      { key: "alertas", label: "Alertas", path: "/admin/hoje/alertas" },
    ],
  },
  {
    key: "vendas",
    label: "Vendas",
    path: "/admin/vendas",
    icon: <ShopOutlined />,
    description: "Fluxo comercial, atendimento e fechamento de pedidos da operacao.",
    section: "principal",
    topbarItems: [
      { key: "painel", label: "Painel", path: "/admin/vendas", accent: "primary" },
      { key: "orcamentos", label: "Orcamentos", path: "/admin/vendas/orcamentos" },
      { key: "pedido-rapido", label: "Pedido rapido", path: "/admin/vendas/pedido-rapido" },
      { key: "recebimentos", label: "Recebimentos", path: "/admin/vendas/recebimentos" },
    ],
  },
  {
    key: "producao",
    label: "Producao",
    path: "/admin/producao",
    icon: <ToolOutlined />,
    description: "Lotes, consumo de insumos, custos e validades da producao.",
    section: "principal",
    topbarItems: [
      { key: "visao-geral", label: "Visao geral", path: "/admin/producao", accent: "primary" },
      { key: "nova-producao", label: "Nova producao", path: "/admin/producao/nova-producao" },
      { key: "lotes", label: "Lotes", path: "/admin/producao/lotes" },
      { key: "consumo", label: "Consumo de insumos", path: "/admin/producao/consumo-insumos" },
      { key: "custos", label: "Custos", path: "/admin/producao/custos" },
      { key: "validades", label: "Validades", path: "/admin/producao/validades" },
    ],
  },
  {
    key: "produtos",
    label: "Produtos",
    path: "/admin/produtos",
    icon: <AppstoreOutlined />,
    description: "Catalogo, status comercial e saude de estoque dos produtos.",
    section: "principal",
    topbarItems: [
      { key: "todos", label: "Todos", path: "/admin/produtos", accent: "primary" },
      { key: "ativos", label: "Ativos", path: "/admin/produtos/ativos" },
      { key: "inativos", label: "Inativos", path: "/admin/produtos/inativos" },
      { key: "estoque-baixo", label: "Estoque baixo", path: "/admin/produtos/estoque-baixo" },
      { key: "novo-produto", label: "Novo produto", path: "/admin/produtos/novo-produto" },
    ],
  },
  {
    key: "estoque",
    label: "Estoque",
    path: "/admin/estoque",
    icon: <InboxOutlined />,
    description: "Controle de saldos, entradas, saidas e alertas operacionais.",
    section: "principal",
    topbarItems: [
      { key: "resumo", label: "Resumo", path: "/admin/estoque", accent: "primary" },
      { key: "movimentacoes", label: "Movimentacoes", path: "/admin/estoque/movimentacoes" },
      { key: "reposicao", label: "Reposicao", path: "/admin/estoque/reposicao" },
    ],
  },
  {
    key: "clientes",
    label: "Clientes",
    path: "/admin/clientes",
    icon: <TeamOutlined />,
    description: "Cadastro, relacionamento e historico comercial dos clientes.",
    section: "principal",
    topbarItems: [
      { key: "todos", label: "Todos", path: "/admin/clientes", accent: "primary" },
      { key: "com-telefone", label: "Com telefone", path: "/admin/clientes/com-telefone" },
      { key: "ultima-compra", label: "Ultima compra", path: "/admin/clientes/ultima-compra" },
      { key: "favoritos", label: "Favoritos", path: "/admin/clientes/favoritos" },
    ],
  },
  {
    key: "caixa",
    label: "Caixa",
    path: "/admin/caixa",
    icon: <DollarCircleOutlined />,
    description: "Saldo, lancamentos, contas e fechamento financeiro da operacao.",
    section: "principal",
    topbarItems: [
      { key: "entradas", label: "Entradas", path: "/admin/caixa", accent: "primary" },
      { key: "saidas", label: "Saidas", path: "/admin/caixa/saidas" },
      { key: "contas", label: "Contas", path: "/admin/caixa/contas" },
      { key: "recebiveis", label: "Recebiveis", path: "/admin/caixa/recebiveis" },
      { key: "fechamento", label: "Fechamento", path: "/admin/caixa/fechamento" },
    ],
  },
  {
    key: "mais",
    label: "Mais",
    path: "/admin/mais",
    icon: <BarChartOutlined />,
    description: "Area de acesso aos modulos complementares e expansoes futuras.",
    section: "principal",
    topbarItems: [
      { key: "precificacao", label: "Precificacao", path: "/admin/precificacao" },
      { key: "pedidos", label: "Pedidos", path: "/admin/pedidos" },
      { key: "fornecedores", label: "Fornecedores", path: "/admin/fornecedores" },
      { key: "relatorios", label: "Relatorios", path: "/admin/relatorios" },
      { key: "configuracoes", label: "Configuracoes", path: "/admin/configuracoes" },
      { key: "loja", label: "Loja", path: "/loja" },
    ],
  },
  {
    key: "precificacao",
    label: "Precificacao",
    path: "/admin/precificacao",
    icon: <CalculatorOutlined />,
    description: "Custos, margens e parametros de formacao de preco.",
    section: "mais",
  },
  {
    key: "pedidos",
    label: "Pedidos",
    path: "/admin/pedidos",
    icon: <ShoppingCartOutlined />,
    description: "Pedidos, entregas e acompanhamento do pos-venda.",
    section: "mais",
  },
  {
    key: "fornecedores",
    label: "Fornecedores",
    path: "/admin/fornecedores",
    icon: <TruckOutlined />,
    description: "Base de compras, abastecimento e relacao com fornecedores.",
    section: "mais",
  },
  {
    key: "relatorios",
    label: "Relatorios",
    path: "/admin/relatorios",
    icon: <BarChartOutlined />,
    description: "Analises operacionais, comerciais e financeiras.",
    section: "mais",
  },
  {
    key: "configuracoes",
    label: "Configuracoes",
    path: "/admin/configuracoes",
    icon: <SettingOutlined />,
    description: "Parametros da operacao e governanca da migracao.",
    section: "mais",
  },
  {
    key: "loja-admin",
    label: "Loja",
    path: "/loja",
    icon: <ExperimentOutlined />,
    description: "Entrada para a experiencia publica da loja no mesmo frontend.",
    section: "mais",
  },
];
